import './globals.css';
import type { Metadata } from 'next';
import { Inter, Krub } from 'next/font/google';
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ['latin'] });
const krub = Krub({ 
  weight: ['400', '500', '600', '700'],
  subsets: ['latin', 'thai'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={krub.className} suppressHydrationWarning>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
